### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mattjmorrison-imt** [JarrodCTaylor/github-pull-dashboard#1]
I was hoping this wouldn't be necessary, but there may need to be a reviewer/reviewee toggle... here is why....  As the reviewer if a build a failing I don't want to look at it... As a reviewee if a build is failing I do because I need to fix it...

**Comment by JarrodCTaylor** [comment]
I need to determine if the build status is available in the api info.  If that is available then it could be used to determine action verse sleep.  If the build is failing even if you were the last one to create an event you still need to take action. Is that what you are going for?

**Comment by mattjmorrison-imt** [comment]
That is true, unless you are the reviewer... maybe we could simplify this by just basing it off of tags...

**Comment by JarrodCTaylor** [comment]
I wouldn't matter if you are the reviewer of not. The action vs sleep logic currently is

```
if opened_by != last_event_by:
    True
False
```

We could update that to be

```
if opened_by != last_event_by or build_failing:
    True
False
```

Assuming we can get the build info.

**Comment by mattjmorrison-imt** [comment]
I think it does matter... If I'm the reviewer and I didn't open the issue and I haven't commented on it and the build it failing... I don't care about it... if I opened the PR and the build is failing then I do care about it. If the build is failing the only person that needs to take action is the one who opened it...

**Comment by JarrodCTaylor** [comment]
The logic above was wrong / incomplete. I think we have enough info to make the determination without the need for the user to toggle something. 

Something more like this

```
if build_failing and current_user == pr_opened_by:
    return True
if current_user != last_event_by and build_passing:
    returnTrue
return False
```

**Comment by mattjmorrison-imt** [comment]
I think that works.
