### ISSUE TITLE
Labels?

### ISSUE THREAD

**Issue by mattjmorrison-imt** [JarrodCTaylor/github-pull-dashboard#3]
How would you feel about adding labels to the UI? This is still a work in progress, but I've been trying to keep this up-to-date as we get into the whole PR workflow: https://github.com/imtapps/dev-docs/blob/pull-requests/pull-requests.md#labels

**Comment by JarrodCTaylor** [comment]
This shouldn't be "hard" assuming that the info is available. Just a matter of digging through the info that comes back from the api and likely making another ajax call per PR.

**Comment by JarrodCTaylor** [comment]
I am unable to find where we can acquire this information through the github api. If you can find it somewhere I am open to include it, but as it doesn't seem to exist I will close this for now. If you can find it just reopen this bad boy.

**Comment by mattjmorrison-imt** [comment]
https://developer.github.com/v3/issues/labels/#list-labels-on-an-issue
