### ISSUE TITLE
Killing me Smalls

### ISSUE THREAD

**Issue by mattjmorrison-imt** [JarrodCTaylor/github-pull-dashboard#4]
I keep hitting "refresh" to get the new PRs... 

![image](https://cloud.githubusercontent.com/assets/16543537/13015408/82e6fc26-d17e-11e5-8322-d45744be8b34.png)

Can this somehow be tied into Github OAuth or maybe store something in local storage so a refresh doesn't lose the login?

**Comment by JarrodCTaylor** [comment]
If you just click the button again you will get updated information no need to refresh. I looked into doing the OAuth thing but that requires a secret key which would require a backend which I was trying to avoid. It seemed a little odd to store someone's password in local storage although that is certainly an option.

**Comment by mattjmorrison-imt** [comment]
Yeah, I figured the OAuth thing would be something like that... and the whole password in local storage also probably isn't ideal... is there someway to hijack the browser's refresh button... like adding a `window.onbeforeunload` warning or something?

**Comment by JarrodCTaylor** [comment]
That could be done. However, that just creates a pop-up box asking you to confirm if you want to refresh. The function to refresh the pull requests can go in there as well, but you will still have to click the `I don't want to refresh` button. It would be a safeguard preventing you from accidentally refreshing. Would you like that functionality?
