### ISSUE TITLE
Sticky Navigation 

### ISSUE THREAD

**Issue by mattjmorrison** [JarrodCTaylor/github-pull-dashboard#6]
I think it would be nice if these buttons:
![image](https://cloud.githubusercontent.com/assets/150277/13882135/246f57d0-ecf2-11e5-836c-996c7b232608.png)
would be available as you scroll down the page... 

Example use case: someone says, "Hey, did you take a look at my PR" so I pull up my handy dandy github pr dashboard and I scroll to the bottom and I don't see it... It would be nice to be able to click the `Get PRs` button while I'm down there rather than scrolling back to the top or hitting refresh and clicking the confirm dialog deal... 

Just a thought.

**Comment by JarrodCTaylor** [comment]
Which would you rather have / would be more handy? The sticky navigation or replace `SHOW [MY] PRs` with a filter input field and a select box for which field to apply the filter to.

**Comment by mattjmorrison** [comment]
I like the filter idea...

**Comment by JarrodCTaylor** [comment]
So many filtering options
![image](https://cloud.githubusercontent.com/assets/4416952/13953439/fd66bae6-f009-11e5-9834-aa911f971793.png)
