### ISSUE TITLE
Feature Request: Auto-reload

### ISSUE THREAD

**Issue by mattjmorrison-imt** [JarrodCTaylor/github-pull-dashboard#7]
What would you think about adding an auto reload option?

**Comment by JarrodCTaylor** [comment]
How would this work?

**Comment by mattjmorrison-imt** [comment]
Maybe... check a box, then every 3 minutes do what the `Get PRs` button does?

**Comment by JarrodCTaylor** [comment]
The only limitation that we will have, is the number of calls that github allows you every hour.  It takes a lot of calls to populate the app.  I will crunch the numbers and see what a safe minimum refresh time is.

**Comment by mattjmorrison-imt** [comment]
maybe it could just go out to see if there are any new PRs or PRs that were closed and add/remove the ones needed?

**Comment by JarrodCTaylor** [comment]
Closed by https://github.com/JarrodCTaylor/github-pull-dashboard/commit/39d6f69af07590bfcc35ecb65586ac27da5c7ac8

![image](https://cloud.githubusercontent.com/assets/4416952/15034983/cd16ee2e-1241-11e6-8ed1-075c0cf8db9e.png)
